require('tuenhan.telescope')
require('tuenhan.lspconfig')
require('tuenhan.lsp-colors')
require('tuenhan.treesitter')
-- require('tuenhan.completions')
require('tuenhan.lualine')
require('tuenhan.nvim_tree')
require('indent_blankline')
require('tuenhan.indent_blankline')
