#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d         

bspc config border_width         2
bspc config window_gap           12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
# Use alt + left mouse to move and alt + right mouse to resize
bspc config pointer_modifier mod1

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Display settings 

if [[ $(xrandr -q | grep 'HDMI1 connected') ]]; then
  xrandr --output eDP1 --primary --mode 1366x768 --rotate normal --output HDMI1 --mode 1366x768 --rotate normal --right-of eDP1
fi

# xrandr --output eDP1 --primary --mode 1366x768 --rotate normal --output HDMI1 --mode 1366x768 --rotate normal --right-of eDP1
# xrandr --output "HDMI1" --set audio force-dvi --mode 1366x768
# # # xrandr --output "eDP1" --auto --output "HDMI1" --right-of "eDP1"
#
# xrandr --output "eDP1" --auto --output "eDP1" --left-of "HDMI1"

# Wallpapers 
feh --bg-scale /home/peter/Bản\ tải\ về/mntfji.jpg 

# Picom (transparent) + animations
picom &


# polybar 
/home/peter/.config/polybar/launch.sh
# Wireless connections (network manager)
nm-applet --indicator & 
# Dunst notifications 
dunst &

# Ibus bamboo type use for Viet Nam: 
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
pidof ibus-daemon > /dev/null || ibus-daemon -drx
