env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  TERM: 'xterm-256color'

window:
  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 24
    y: 24
  decorations: none
  dimensions:
    columns: 80
    lines: 35
  opacity: 0.7

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 1000

  # Scrolling distance multiplier.
  multiplier: 3

# Font configuration
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: 'JetBrains Mono Nerd Font'

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: 'JetBrains Mono Nerd Font'

    # The `style` can be specified to pick a specific face.
    style: Bold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: 'JetBrains Mono Nerd Font'

    # The `style` can be specified to pick a specific face.
    style: Italic

  # Point size
  size: 13

  offset:
    y: 0

  glyph_offset:
    y: 0

# Colors (Poimandres)
colors:
  # Default colors
  primary:
    background: "0x131621"
    foreground: "0xa6accd"

  # Cursor colors
  cursor:
    text: CellBackground
    cursor: CellForeground

  # Search colors
  #
  # Colors used for the search bar and match highlighting.
  search:
    # Allowed values are CellForeground/CellBackground, which reference the
    # affected cell, or hexadecimal colors like #ff00ff.
    matches:
      foreground: "0x1b1e28"
      background: "0xadd7ff"

    focused_match:
      foreground: "0x1b1e28"
      background: "0xadd7ff"


  # Selection colors
  #
  # Colors which should be used to draw the selection area.
  #
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  selection:
    text: CellForeground
    background: "0x303340"

  # Vi mode cursor colors
  #
  # Colors for the cursor when the vi mode is active.
  #
  # Allowed values are CellForeground/CellBackground, which reference the
  # affected cell, or hexadecimal colors like #ff00ff.
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  # Normal colors
  normal:
    black: "0x1b1e28"
    red: "0xd0679d"
    green: "0x5de4c7"
    yellow: "0xfffac2"
    blue: "#435c89"
    magenta: "0xfcc5e9"
    cyan: "0xadd7ff"
    white: "0xffffff"

  # Bright colors
  bright:
    black: "0xa6accd"
    red: "0xd0679d"
    green: "0x5de4c7"
    yellow: "0xfffac2"
    blue: "0xadd7ff"
    magenta: "0xfae4fc"
    cyan: "0x89ddff"
    white: "0xffffff"

cursor:
  # Cursor style
  #
  # Values for `style`:
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: 'Underline'

  vi_mode_style: 'Underline'
theme: iTerm-Default
